#!/bin/bash
#BATCH --job-name=jupyterlab
#SBATCH -t 3:00:00
#SBATCH -p rome
#SBATCH --cpus-per-task=32
#SBATCH --get-user-env

cd ~
echo "into the Scripts for my project"
export PATH=/home/ybhatti/yusufb/miniconda3/bin:$PATH
source activate ESM
##PORT=`shuf -i 5000-5999 -n 1`
PORT=51525
#PORT=`shuf -i 5000-5999 -n 1`

#OGIN_HOST=${SLURM_SUBMIT_HOST}-pub.snellius.surf.nl
LOGIN_HOST=int5-pub.snellius.surf.nl
BATCH_HOST=$(hostname)
 
echo "To connect to the notebook type the following command from your local terminal:"
echo "ssh -N -J ${USER}@${LOGIN_HOST} ${USER}@${BATCH_HOST} -L ${PORT}:localhost:${PORT}"
echo
echo "After connection is established in your local browser go to the address:"
echo "http://localhost:${PORT}"
#/usr/bin/ssh -N -f -R $PORT:localhost:$PORT snellius

echo "Connect to localhost" 
sed -i '6c\ssh -N -J '"${USER}"'@'"${LOGIN_HOST}"' '"${USER}"'@'"${BATCH_HOST}"' -L '"${PORT}"':localhost:'"${PORT}"'' /home/ybhatti/HPC_Jupyter/ssh_connect.sh


echo "connected to local host ssh -N -J ${USER}@${LOGIN_HOST} ${USER}@${BATCH_HOST} -L ${PORT}:localhost:${PORT}"

jupyter-lab --no-browser --port $PORT #--NotebookApp.max_buffer_size=96636764160

