#!/bin/bash
#SBATCH --job-name=Process_large_data
#SBATCH -t 12:00:00
#SBATCH -p fat_rome
#SBATCH -N 3         # 3 nodes
#SBATCH --get-user-env
#SBATCH --exclusive
#SBATCH -o slurm-%j.out
#SBATCH -e slurm-%j.err

echo "into the Scripts for my project"
export PATH=/home/ybhatti2/miniconda3/bin:$PATH
source activate myenv

export PYTHONPATH=$PYTHONPATH:/home/ybhatti2/HPC_Jupyter/Python_Scripts/
#export PYTHONPATH=$PYTHONPATH:/home/ybhatti/prjs1076/Emulator:/home/ybhatti/prjs1076/Emulator/
export NUMBER_OF_SAMPLES=24000
export BASE_DIR="/home/ybhatti2/prjs1474/Datasets/PPE_Processed_Data/PD/Emulated_data/Implausibility/Var"
mkdir -p "$BASE_DIR"
VARIABLES=(AOD AAOD ANG AOD_Mode_1 AOD_Mode_2 AOD_Mode_3 SSA AI AOD_Mode_Coarse)
VARIABLES=(ERF ERFaci ERFari)

#python -u Generate_New_Samples.py
wait
for VARIABLE_NAME in "${VARIABLES[@]}"; do
    mkdir -p "$BASE_DIR/$VARIABLE_NAME"
    export VARIABLE_NAME
    echo "Part 1 for VARIABLE_NAME=${VARIABLE_NAME}"
    srun --ntasks=1 --nodes=1 python -u Part_1_Emulated.py > log_${VARIABLE_NAME}s.out 2>&1 &
done
wait


# --- Variables to emulate ---

MAX_PARALLEL=3   # how many variables to run at once
count=0

for VARIABLE_NAME in "${VARIABLES[@]}"
do
    echo ">>> Running for VARIABLE_NAME=${VARIABLE_NAME}"
    export VARIABLE_NAME
    #python -u Part_2_Emulate.py > log_${VARIABLE_NAME}.out 2>&1 &
#    srun --ntasks=1 --nodes=1 python -u Part_2_Emulate.py > log_${VARIABLE_NAME}s.out 2>&1 &

    ((count++))
    # When two jobs are running, wait for them to finish before continuing
    if ((count % MAX_PARALLEL == 0)); then
        echo ">>> Waiting for current batch to finish..."
        wait
        echo ">>> Continuing with next batch..."
    fi
    sleep 15
done

wait
echo "✅ All variable emulations completed."

